[tox]
envlist =
    clean
    py{310,311,312,313}-django52
    coverage-html
skipsdist = True
skip_missing_interpreters = True
isolated_build = True

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv:clean]
deps = coverage
commands = -coverage erase

[testenv:coverage-html]
deps = coverage
commands =
    -coverage combine --append
    coverage html --include="./src/*" --omit="*/test*"

[testenv:coverage-xml]
deps = coverage
commands =
    -coverage combine --append
    coverage xml --include="./src/*" --omit="*/test*"

[testenv]
passenv =
    POSTGRES_DB
    POSTGRES_USER
    POSTGRES_PASSWORD
    POSTGRES_HOST
    POSTGRES_PORT

deps =
    coverage
    Django>=5.2,<5.3
    psycopg[binary]>=3.1

setenv =
    LC_ALL=C.UTF-8
    LANG=C.UTF-8
    PYTHONPATH = {toxinidir}/src:{toxinidir}
    PYTHONWARNINGS=once::DeprecationWarning

commands =
    coverage run -p runtests.py {posargs}
